### PR TITLE
deps: Update dugite to 2.5.2

### PR DESCRIPTION
**Pull request by DeeDeeG**
This should add support for ARM Linux.

Once we bump `dugite` here and in `github` package, I expect the `github` package may start working in Pulsar on ARM Linux? See release notes for `dugite` here: https://github.com/desktop/dugite/releases

### CODE REVIEW

**Comment by DeeDeeG** [comment]
There's no `dugite` 2.5.2 on the npm package registry... I opened an issue asking them to publish it: https://github.com/desktop/dugite/issues/554

It's not really relevant to us, thankfully, since we're not building for 32-bit x86 Linux. For now, I can update to 2.5.1 instead in this PR, but I would keep this PR open for a few days to see if they get a chance to publish 2.5.2 to the npm registry.

**Comment by DeeDeeG** [comment]
Okay, dugite 2.5.2 was published to the npm package registry!

Re-bumping here (I forgot to update `package-lock.json` the first time, apparently.) And this should be good to go! I'll mark it as ready for review.

**Review by confused-Techie — APPROVED** [review]
Love to see this! Thanks for keeping the bump pinned to reduce our concern in these deps becoming out of date. As long as this is followed up with a bump in `github` then I fully support merging this one in, thanks for the effort!

**Comment by DeeDeeG** [comment]
I think I'm gonna make sure the `github` side of things is ready to go at the same time to keep things synced up.

Appreciate the review! One less plate to spin to make sure it all lines up. This part is "good" but parked until the other half is ready I guess? (Or if someone beats me to it, feel free to merge this + a bump at `github` repo!)

I do intend to get to it "soonish", not 100% sure if before/after Regular, but might catch up regarding timing here or on Discord soon to sort that out.

**Comment by DeeDeeG** [comment]
Merging this with a PR to be posted at github repo more or less immediately after.

(I need to merge this first, then get the SHA of the merge commit from merging this, so I can bump `whats-my-line` dependency under `github` package's package.json to that SHA.)

BRB merging and then second PR. (Thanks again for review!)

**Comment by DeeDeeG** [comment]
Welp, I forgot this repo bumped `superstring` already, so until I've set everything up to sync the `superstring` bump across all three packages that depend on it, I have to make "just the dugite bump" be its own branch again, like last time. (Or some similar solution, but I'll do that again.)

See this branch: [`just-the-dugite-2.5.2-bump`](https://github.com/pulsar-edit/whats-my-line/tree/just-the-dugite-2.5.2-bump)

And now, the PR over at the github package's repo: https://github.com/pulsar-edit/github/pull/39

**Pull request merged**
